### ISSUE TITLE
Insert implementation looks wrong.

### ISSUE THREAD

**Issue by vignesh-j-shetty** [CalebLBaker/b-tree#3]
If an node is full, you to have recursively split parent node also until non full parent node found.

**Comment by CalebLBaker** [comment]
That is correct. I created this repository years ago when I was first learning how to program, so I'm not surprised to hear that it has bugs.

I am no longer maintaining this repository and so I won't be fixing this but feel free to fork and fix it yourself if you want. Or use a b-tree implementation from a better tested and actively maintained repository (e.g. https://github.com/abseil/abseil-cpp).
